# Generated by Django 3.0.8 on 2020-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(max_length=50),
        ),
    ]
